### ISSUE TITLE
Unhandled Runtime Error: Hydration failed

### ISSUE THREAD

**Issue by MimaoQiuQiu** [Cubeseed/Frontend#15]
The error looks like this:
<img width="728" alt="cubeerror" src="https://github.com/Cubeseed/Frontend/assets/93206137/e68a44cd-93af-4b9f-8e9f-689ffc825da5">
************************************************************************
What I know is this error is related to SSR and CSR in Next.js. It indicates that there is a mismatch related to a `<form>` element. 

This error generally occurs when the initial HTML rendered on the server is different from what is generated on the client side. Here are some of my guesses of why this happens:
1. Data fetching:
When form content contains data fetched asynchronously, but not available on the server. 
2. Conditional rendering:
There are some parts of the code based on client-side data when rendering.

Unfortunately, I'm not able to come up with a solution. If you guys have any thought about this error, we can discuss it. Thank you very much!

**Comment by MimaoQiuQiu** [comment]
Add on:
I run the code in my local environment using npm run dev. It will open at localhost:3000. The error pops up the moment I open the localhost link.

**Comment by PjSingh22** [comment]
- I changed the form tag within the ServiceForm component to a div and it fixed the issue of displaying the hydration error. 
- Need to do testing to make sure everything still works 

this article shines a light on what went wrong: https://stackoverflow.com/questions/1759006/embed-an-html-form-within-a-larger-form

**Comment by sgarciahelguera** [comment]
Hi @PjSingh22, I just added you to the front end team, can you make a pull request for this? thanks!!

**Comment by mihrab34** [comment]
> * I changed the form tag within the ServiceForm component to a div and it fixed the issue of displaying the hydration error.
> * Need to do testing to make sure everything still works
> 
> edit: everything seems to be working. Can't push up branch with changes due to not having rights to. So if anyone wants to implement the simple change please do.
> 
> this article shines a light on what went wrong: https://stackoverflow.com/questions/1759006/embed-an-html-form-within-a-larger-form

I think you have access now, so you should be able to open a PR with the fix

**Comment by PjSingh22** [comment]
Can't push it on my end. @sgarciahelguera @mihrab34 
![image](https://github.com/Cubeseed/Frontend/assets/47789898/690d3c02-752f-4010-b33c-de64bb6624be)

**Comment by myspace20** [comment]
Fixed 
There are a few things  to be addressed though.

**Comment by sgarciahelguera** [comment]
> Fixed There are a few things to be addressed though.

About this issue? or something else?

**Comment by myspace20** [comment]
Yes
