### ISSUE TITLE
Migrate Landing page to this repo

### ISSUE THREAD

**Issue by tayjlim** [Cubeseed/Frontend#22]
Was wondering if anyone is going to merge the landing page repo into this front end so we do not reuse the components.

**Comment by abu-hasib** [comment]
do you mean the one at cubeseed.com.ng?

**Comment by tayjlim** [comment]
I meant merging the landingpage repo to this current repo

**Comment by cgrq** [comment]
The landing page is now apparently deprecated and has been replaced by a Wordpress site in case anyone else is looking into this
