### ISSUE TITLE
Update README file 

### ISSUE THREAD

**Issue by KrownWealth** [Cubeseed/Frontend#3]
I noticed the README file does not give a detailed first time glance of how to contribute on the project. I'm hoping to improve/update the README file by:

1. Give the list of the tech stack used in the project
2. How to get started with the project repo
3. How to contribute
4. How to create a Pull Request to avoid merge conflicts

**Comment by abu-hasib** [comment]
I believe for this you can go ahead and make a PR and link this issue when you update the readme
This [doc](https://docs.google.com/document/d/1otSVVp7G5-K1eNmDUV5-jHWlj8JHG9KH3xgwZGicbBg/edit) list some of the tech stack

**Comment by KrownWealth** [comment]
Thanks for the response, I will go ahead and then make a PR

**Comment by KrownWealth** [comment]
Another issue has been raised to address this, that one seems specific so am closing this issue.
