### ISSUE TITLE
No address input field on sign up page

### ISSUE THREAD

**Issue by PjSingh22** [Cubeseed/Frontend#32]
- the back end route to create a userprofile requires an address input field. 
- currently the front end sign up form does not have an address input field.

**Comment by MimaoQiuQiu** [comment]
I see an input field for the Farm Address during the set-up profile to farm-verification process. That's the only address I found related to a user on the current Figma design. So, I guess maybe they want to use the farm address as the address? But I'm not sure about that. If a user wants to enter both his personal address and farm's address, then there should be some changes to the UI design.

**Comment by PjSingh22** [comment]
yeah this was a misunderstanding on my part. I was looking at the userprofile route and thought that was the one to hit when registering a user. Going to close this issue
