### ISSUE TITLE
Project folders structure/re-structuring

### ISSUE THREAD

**Issue by KrownWealth** [Cubeseed/Frontend#4]
Before forking the repo and making our contributions, I would suggest we have the repo folders structure for easier collaboration and merging of PR

For instance inside the src folder we have:
assets
components
inside the component folder we can have

1. auth folder
a. login
b. sign_up
c. forgot_pass

2.  retail_web folder
a. retailWebCategory
b. singlCategory

context
hooks
pages
styles

And so on, with this each member working on implementing one or two UI will know where and how to create folders for his/her assigned tasks.

**Comment by abu-hasib** [comment]
@KrownWealth 
This is a good suggestion.
I have a few recommendations

The components folder should only contain reusable components

I will suggest a structure like this:

app -  contains folders like (auth) (dashboard) etc.
assets
components - all reusable components like nav, footer, etc
config - all config related
hooks
pages
styles
types - optional

Other suggestions are welcome

**Comment by abu-hasib** [comment]
@MimaoQiuQiu @jezraelhope

**Comment by goodylove** [comment]
same here ... i was confuse after cloning the repo

**Comment by MimaoQiuQiu** [comment]
Good. I noticed that at the first time when I got the base code. We can and are definitely going to do that before its getting big.

**Comment by KrownWealth** [comment]
I authored the thread, let me make the changes, as I've been sent some docs to add to the readme.

**Comment by MimaoQiuQiu** [comment]
Do you mean that you want to restructure all folders by yourself? @KrownWealth

**Comment by KrownWealth** [comment]
I am not, because if I do there might be many conflicts merging for those that have gotten their PR merged. 

Since we have a meeting today, I think should be ironed out.

**Comment by MimaoQiuQiu** [comment]
Sorry for my misunderstanding, we'll talk about this at the meeting. I think if we want to restructure all the things we have currently, we have to make it done before any new merge comes. Also, restructuring needs to be done fast.

**Comment by MimaoQiuQiu** [comment]
We can ask Bedford at the meeting about how much time we may have to restructure the folders.

**Comment by KrownWealth** [comment]
Yes sure, are you the Discord channel?

**Comment by jezraelhope** [comment]
Sorry, I just got back. This looks great and definitely an improvement to our current structure. Have you guys discussed how it will be implemented?

**Comment by abu-hasib** [comment]
yes, it was discussed in Saturday's meeting. @MimaoQiuQiu is assigned to it.

**Comment by sgarciahelguera** [comment]
@MimaoQiuQiu your progress on this is looking good, I am looking forward to seeing a pull request so that others here that missed the meeting can comment on it.
